version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: library
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://root:root@db/library